### ISSUE TITLE
disco_xform_utils.py failed to import InferenceHelper. Please ensure that AdaBins directory is in the path (i.e. via sys.path.append('./AdaBins') or other means).

### ISSUE THREAD

**Issue by isaacsmeele** [MohamadZeina/Disco_Diffusion_Local#30]
disco_xform_utils.py failed to import InferenceHelper. Please ensure that AdaBins directory is in the path (i.e. via sys.path.append('./AdaBins') or other means).
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [4], in <cell line: 125>()
    133       wget("https://cloudflare-ipfs.com/ipfs/Qmd2mMnDLWePKmgfS8m6ntAg4nhV5VkUyAydYBp8cWWeB7/AdaBins_nyu.pt", f'{PROJECT_DIR}/pretrained')
    134     sys.path.append(f'{PROJECT_DIR}/AdaBins')
--> 135   from infer import InferenceHelper
    136   MAX_ADABINS_AREA = 500000
    138 import torch

ImportError: cannot import name 'InferenceHelper' from 'infer' (/root/anaconda3/lib/python3.9/site-packages/infer/__init__.py)

**I have tried uninstalling and reinstalling infer but nothing works**

**Comment by Yancke** [comment]
Im having this exact issue atm. Did you ever find a solve ? @isaacsmeele

**Comment by illtellyoulater** [comment]
I don't know if this is the result of a poor coding quality, but the AdaBins error message is highly misleading because it shows up before the part of the code responsible for installing AdaBins itself is even reached (yes I know it's weird...)

Once I discovered that, I inspected more closely the cell output which included the error, and I found that below the "fake" AdaBins error message there was another error relative to a missing package called "ntlk".

So I installed it with `conda install ntlk`, stopped the notebook, restarted it and ran it again cell by cell...
And once again the misleading AdaBins error message showed up... this time hiding below it another error message about another missing package ("pandas").

I installed that one also and repeated this for all the missing packages...
Once I did that, the code finally reached the point where it actually installed AdaBins.
But even after that the Adabins error was still showing. However I kept running the code in the other cells and I could generate images without problems.

In case someone may find it helpful, this is the list of packages that I had to install

```
conda install opencv nltk pandas
conda install matplotlib -c conda-forge 
```

Another minor error I had to deal with was that the torch libs installed in my system were compiled without CUDA support, so I had to uninstall and reinstall them with:

```
pip uninstall pytorch torchvision torchaudio 
conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia
```

I hope this helps!

**Comment by aditya-xq** [comment]
While running locally, I changed the import statement everywhere to this and it worked:

```
from AdaBins.infer import InferenceHelper
````

The AdaBins folder is in the project directory. Not sure why the sys path doesn't get updated.

**Comment by illtellyoulater** [comment]
Yes, contrary to what I said in my earlier comment (which I have now corrected), and in accordance to what you said, I could see that after installing all the other libs it still complained about Adabins not being detected, but this doesn't prevent the code in other cells to run correctly, including the image generation cell.

**Comment by Rage4Me** [comment]
14Dec2022 - Having the same issue and error message.  Neither solution here is working.  (Disco Diffusion v5.61)
So what happens if I just change:  USE_ADABINS = True to USE_ADABINS = False?

**Comment by MohamadZeina** [comment]
@Rage4Me try it and let us know ;)

You might have to also remove other references to adabins, ie comment out the imports themselves
